### ISSUE TITLE
It's nice to have icon on notification

### ISSUE THREAD

**Issue by rbnmax** [luc-ass/docker-telegram-notifier#22]
It's nice, now we see notifications with icons.

I think this 🔴 red icon is better than this one 🛑.

Can you update it?

**Comment by luc-ass** [comment]
Hi @rbnmax, thank you for your input. What platform (iOS, Android, Windows, etc.) are you using? Can you upload a screenshot comparing 🛑 and 🔴? For me on iOS, iPadOS and macOS they look quite similar.

**Comment by rbnmax** [comment]
It looks like this..
![old](https://user-images.githubusercontent.com/113860366/191241076-04802739-1e3b-4dc6-b3a3-d3ae16caa3ed.png)
This would be nice..
![new](https://user-images.githubusercontent.com/113860366/191241206-de0e2349-800e-4238-b311-dddab7590169.png)

I see the different on windows and android.

**HTML-code**
Old - &#128721
New - &#128308

**Comment by luc-ass** [comment]
Difference for documentation:
![Bildschirm­foto 2022-09-21 um 06 35 36](https://user-images.githubusercontent.com/3263257/191415313-6008299e-e44a-4cb5-aecc-d38c78de09f6.jpg)
![Bildschirm­foto 2022-09-21 um 06 35 53](https://user-images.githubusercontent.com/3263257/191415322-661bfecf-9815-4378-aada-458c63ad3eab.jpg)

**Comment by luc-ass** [comment]
As there are circles in more colours, do you think all of them should be green/yellow/red circles?

- 🔴 stopped
- 🟢 started/starting
- 🟢 healthy
- 🟠 unhealthy

What do you think?

**Comment by rbnmax** [comment]
No! only red should be circle. Different shapes are also good to distinguish them. The red shape we have now looks like a small image has been zoomed.

**Comment by luc-ass** [comment]
Agreed, my initial intent was to mimic a stop sign, but that only works wit openmemoji. 

I will also update the documentation on how to implement custom templates.

**Comment by luc-ass** [comment]
merged #23

**Comment by luc-ass** [comment]
@rbnmax I've updated the icons to differentiate between normal and non-normal exit codes. I'd love to hear your feedback on this.
