### ISSUE TITLE
Disable link preview in notification?

### ISSUE THREAD

**Issue by rbnmax** [luc-ass/docker-telegram-notifier#24]
It's annoying have a big message like this.

![link-preview](https://user-images.githubusercontent.com/113860366/191997584-a80ccb38-adb2-404b-baed-89d61905f4c3.png)

**Comment by luc-ass** [comment]
Seems linke telegram does this automatically. If you find something in their documentation, I'd be happy to implement it.

**Comment by rbnmax** [comment]
I think we have to add send message parameter `disable_web_page_preview=True` on the message template. Refer: [https://core.telegram.org/bots/api#sendmessage](https://core.telegram.org/bots/api#sendmessage)

**Comment by luc-ass** [comment]
Sounds like an option. I'll look into it as soon as I have some time. Would `disable_notification` be interesting from your point of view? "Positive alerts" can be anoying at times...

**Comment by rbnmax** [comment]
These options can be environment variables, so can user select what they want.

**Comment by luc-ass** [comment]
Please have a look at the PR #25. Can you think of any use-case where loading the preview would be advantageous?

**Comment by rbnmax** [comment]
In this case admin users already have enough knowledge about where the docker container image is coming from. So they don't need many information about it in every single notification... It's enough a simple url about it (what we have alredy). and the notification with link preview looks like adds between notification 🙄.

**Comment by luc-ass** [comment]
Looks like it's working as of v1.2.1. Don't hesitate to reopen this issue if you encounter problems with the link generation.
