### ISSUE TITLE
Split regular shutdown from errors

### ISSUE THREAD

**Issue by luc-ass** [luc-ass/docker-telegram-notifier#8]
As of now the templates only include `container_die`, but do not distinguish by exit code. This alerts, even if the container is shut down on purpose (exit code 0).

Options:
- split by exit code (i.e. 0 vs. not 0)
- use different status messages (to be determined)

**Comment by luc-ass** [comment]
@rbnmax as you are involved: What status codes do you receive on wich actions from your containers?
I get the following codes:
- 0: container stopped itself (expected)
- 137: container was stopped from portainer (expected) but can be out-of-memory

But it's difficult to determine which errors to alert on and which to deliver silently:
- Exit Code 0: Absence of an attached foreground process
- Exit Code 1: Indicates failure due to application error
- Exit Code 137: Indicates failure as container received SIGKILL (Manual intervention or ‘oom-killer’ [OUT-OF-MEMORY])
- Exit Code 139: Indicates failure as container received SIGSEGV
- Exit Code 143: Indicates failure as container received SIGTERM

**Comment by rbnmax** [comment]
I restart container with cronjob, I get 0 mostly, sometime even 137. I use also portainer.  I get 137 mostly when i restart from portainer, even 0 sometime. I didn't got any other failure  yet. 
_(sorry for late reply)_

**Comment by luc-ass** [comment]
Thank you for your response. I am still unsure whether to mute some of those notifications...
