### ISSUE TITLE
Sending messages to a specific topic in groups

### ISSUE THREAD

**Issue by Antosha42** [luc-ass/docker-telegram-notifier#80]
I came across the fact that I need the bot not to send messages to General, but to send them to a specific topic.
Why not add this feature?

**Comment by luc-ass** [comment]
Can you provide an example? I am not quite sure what the use case is.
If you can, I would happily accept pull requests to extend the functionality.

**Comment by Antosha42** [comment]
![image](https://github.com/luc-ass/docker-telegram-notifier/assets/55610823/319991b4-873b-46c3-ba72-86b0b9d40b1d)
![image](https://github.com/luc-ass/docker-telegram-notifier/assets/55610823/ffd3baf2-4d73-44e8-bfc1-cead57fbd868)
something like this

**Comment by luc-ass** [comment]
Interesting. I've never used it like this. Have you found a reference in telegrams API?

**Comment by luc-ass** [comment]
As per [this article](https://medium.com/@rezvovvad/send-notifications-to-a-specific-topic-in-the-telegram-chat-1f570b7ab929), you would need to send the thread id. Doesn't sound too complicated. Do you think you can add this? I am on vacation right now and don't have easy access to my dev-environment.

**Comment by luc-ass** [comment]
The underlying `telegraf` doesn't support this for messages, as far as I can see: [LINK](https://telegraf.js.org/classes/Telegram.html#sendMessage)

**Comment by Antosha42** [comment]
> As per [this article](https://medium.com/@rezvovvad/send-notifications-to-a-specific-topic-in-the-telegram-chat-1f570b7ab929), you would need to send the thread id. Doesn't sound too complicated. Do you think you can add this? I am on vacation right now and don't have easy access to my dev-environment.

I'm not that good at developing bots for Telegram, but I can try

**Comment by Antosha42** [comment]
> The underlying `telegraf` doesn't support this for messages, as far as I can see: [LINK](https://telegraf.js.org/classes/Telegram.html#sendMessage)

While I was looking for information, I came across this discussion

https://github.com/telegraf/telegraf/discussions/1811

**Comment by luc-ass** [comment]
> > The underlying `telegraf` doesn't support this for messages, as far as I can see: [LINK](https://telegraf.js.org/classes/Telegram.html#sendMessage)
> 
> While I was looking for information, I came across this discussion
> 
> [telegraf/telegraf#1811](https://github.com/telegraf/telegraf/discussions/1811)

Great find! I'll leave this here for later:
https://github.com/telegraf/telegraf/discussions/1811#discussioncomment-5308598

**Comment by luc-ass** [comment]
Hey there, I've created a branch with the option to set `TELEGRAM_NOTIFIER_THREAD_ID` as environment variable (see [branch](https://github.com/luc-ass/docker-telegram-notifier/tree/post-to-thread)). You should be able to try it out by specifying `docker-telegram-notifier:1.4.0-beta.1`.

Let me know how it goes!

**Comment by luc-ass** [comment]
My quick testing works. Reverting to the regular method also works.

**Comment by luc-ass** [comment]
Implemented in 1.4.0
